default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root

development:
  <<: *default
  database: data_development

production:
  <<: *default
  database: database_production
  username: root
  password: root
  host: localhost
  port: 5432
