# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 98bf3c6cd201ea6a6a443b879f3968469f41e11e2dd54460258739f5e659d7718acb4f89704d46058f83b254fecd5bb119c205d8c3d3b31b6e898eeb5f4c6c72

test:
  secret_key_base: bf728b02d7ed7b9f5b15ed586314c1c82bf36b4c427f7f9787d230a2ab7f162a9aa54845642916a94d64c1d163cb8570fbe336220f7771d863727a6b7d46b7a6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
